/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-10-14 06:36:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.TreeMap;
import java.awt.Label;
import java.util.Iterator;
import java.util.stream.Collector;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.util.HashMap;
import Operations.SMSdb;
import java.util.List;
import java.util.Map;
import modle.Account;
import java.util.ArrayList;
import com.google.gson.Gson;
import Database.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Database");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.awt.Label");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.stream.Collectors");
    _jspx_imports_classes.add("Operations.SMSdb");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.stream.Stream");
    _jspx_imports_classes.add("java.util.TreeMap");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.google.gson.Gson");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.util.stream.Collector");
    _jspx_imports_classes.add("modle.Account");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("=========================================================\r\n");
      out.write(" Light Bootstrap Dashboard - v2.0.1\r\n");
      out.write("=========================================================\r\n");
      out.write("\r\n");
      out.write(" Product Page: https://www.creative-tim.com/product/light-bootstrap-dashboard\r\n");
      out.write(" Copyright 2019 Creative Tim (https://www.creative-tim.com)\r\n");
      out.write(" Licensed under MIT (https://github.com/creativetimofficial/light-bootstrap-dashboard/blob/master/LICENSE)\r\n");
      out.write("\r\n");
      out.write(" Coded by Creative Tim\r\n");
      out.write("\r\n");
      out.write("=========================================================\r\n");
      out.write("\r\n");
      out.write(" The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.  -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"76x76\"\r\n");
      out.write("	href=\"./assets/img/apple-icon.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"./assets/img/favicon.ico\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("<title>DashBoard | Textware Daily SMS Count</title>\r\n");
      out.write("<meta\r\n");
      out.write("	content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'\r\n");
      out.write("	name='viewport' />\r\n");
      out.write("<!--     Fonts and icons     -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700,200\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\" />\r\n");
      out.write("<!-- CSS Files -->\r\n");
      out.write("<link href=\"./assets/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"./assets/css/light-bootstrap-dashboard.css?v=2.0.0 \"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<!-- CSS Just for demo purpose, don't include it in your project -->\r\n");
      out.write("<link href=\"./assets/css/demo.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script\r\n");
      out.write("	src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\"\r\n");
      out.write("	type=\"text/javascript\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://canvasjs.com/assets/script/canvasjs.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

		Gson gsonObj = new Gson();
	ArrayList<Account> _AccountDetails = new ArrayList<>();

	boolean isSuccess;
	Connection connection;
	Statement statement;
	ResultSet resultSet;

	String[] months = {"January", "February", "March", "April", "May", "June", "July", "August", "Sepetember", "October",
			"November", "December"};
	try {

		// Call to the database connection
		connection = DBConnection.GetConnection();

		statement = connection.createStatement();

		String _Sql = "SELECT Year(Date) , Month(Date) , sum(Msg_Count) FROM daily_sms_report.account group by MONTH(Date) , Year(Date) order by Year(Date) Asc";

		resultSet = statement.executeQuery(_Sql);

		if (resultSet.next()) {

			do {

		String _YearNumber = resultSet.getString(1);
		String _MonthNumber = resultSet.getString(2);
		int _MsgCount = resultSet.getInt(3);

		Account account = new Account(_YearNumber, _MonthNumber, _MsgCount);

		_AccountDetails.add(account);

			} while (resultSet.next());
		}

	} catch (Exception e) {

		e.printStackTrace();
	}

	Map<String, List<Account>> mappedData = new HashMap<>();

	for (Account data : _AccountDetails) {

		if (mappedData.containsKey(data.getAccountName())) {

			mappedData.get(data.getAccountName()).add(data);
		} else {
			List<Account> tempList = new ArrayList<Account>();
			tempList.add(data);
			mappedData.put(data.getAccountName(), tempList);
		}

	}

	System.out.println("Dataaaaaaaa" + mappedData);
	Map<String, List<Account>> sortedMap = new TreeMap<String, List<Account>>(mappedData);

	Map<Object, Object> map = null;
	//List<Map<Object, Object>> list = new ArrayList<Map<Object, Object>>();
	List<List<Map<Object, Object>>> mapList = new ArrayList<List<Map<Object, Object>>>();

	for (Map.Entry<String, List<Account>> entry : sortedMap.entrySet()) {
		//  System.out.println("Key = " + entry.getKey() +
		//               ", Value = " + entry.getValue());
		List<Map<Object, Object>> list = new ArrayList<Map<Object, Object>>();

		for (int j = 0; j < months.length; j++) {
			for (int i = 0; i < entry.getValue().size(); i++) {
		String month = months[Integer.parseInt(entry.getValue().get(i).getDate()) - 1];
		//  System.out.println(months[Integer.parseInt(entry.getValue().get(i).getDate())-1] +" " + entry.getValue().get(i).getMsgCount());

		int tempI = j + 1;
		int _month = Integer.parseInt(entry.getValue().get(i).getDate());

		/* System.out.println("Tempp " + tempI);
		System.out.println("Month " + _month);
 */
		if (_month == tempI) {
			map = new HashMap<Object, Object>();
			map.put("label", month);
			map.put("y", entry.getValue().get(i).getMsgCount());

			list.add(map);

		} else {

			map = new HashMap<Object, Object>();
			map.put("label", months[j]);
			map.put("y", 0);
			list.add(map);
		}

			}
		}

		List<Map<Object, Object>> newList = new ArrayList<Map<Object, Object>>();

		for (Map e : list) {

			/* System.out.println("kkkkkkkkkkkk" + e); */
			if (!newList.contains(e)) {

		newList.add(e);

			}
		}

		for (Map f : newList) {
/* 
			System.out.println("jjjjjjjjjjjjjjjjjj" + f); */
		}

		Object label = new Object();
		Object count = new Object();
		Object obj = 0;
		//Object january = "January";
		Map<Object, Object> el = new HashMap<Object, Object>();

		List<Map<Object, Object>> removeList = new ArrayList<Map<Object, Object>>();
		for (Map e : newList) {

			//label = january;

			System.out.println(e.get("label"));

		/* 	System.out.println(e.values().toArray()[0]); */
			if (label.equals(e.get("label"))) {

		if (count.equals(obj)) {
			/* System.out.println("I am here now"); */

			removeList.add(el);
		}
		//do nothing
		else if (e.get("y").equals("0")) {
		/* 	System.out.println("I am here now11111111111111111"); */

			//newList.remove(e);
			removeList.add(e);
		}
			} else {
		//do nothing
			}

			label = e.get("label");
			count = e.values().toArray()[0];
		/* 	System.out.println("counttt" + count); */
			el = e;
			System.out.println("ELLL" + el);

		}
		newList.removeAll(removeList);
		/* System.out.println("lllllllllll" + newList); */

		Map<Object, Object> m1 = new HashMap<Object, Object>();
		Map<Object, Object> m2 = new HashMap<Object, Object>();

		m1 = newList.get(0);
		m2 = newList.get(1);

		System.out.println("okkkk" + m1.get("label"));
		if (m1.get("label").equals(m2.get("label"))) {

		/* 	System.out.println("okkkk111" + m1.values().toArray()[0]); */
			if (m1.values().toArray()[0].equals(obj)) {

		newList.remove(0);
			} else if (m2.values().toArray()[0].equals(obj)) {
		newList.remove(1);
			}
		}

		mapList.add(newList);

	}
/* 	System.out.println("I am heree"); */
	for (List v : mapList) {

	/* 	System.out.println("ggggggggggggggg" + v); */
	}

	List<Map<Object, Object>> list1 = new ArrayList<Map<Object, Object>>();
	List<Map<Object, Object>> list2 = new ArrayList<Map<Object, Object>>();
	List<Map<Object, Object>> list3 = new ArrayList<Map<Object, Object>>();
	List<Map<Object, Object>> list4 = new ArrayList<Map<Object, Object>>();
	List<Map<Object, Object>> list5 = new ArrayList<Map<Object, Object>>();

	list1 = mapList.get(0);
	list2 = mapList.get(1);
	list3 = mapList.get(2);
	list4 = mapList.get(3);
	list5 = mapList.get(4);

	/*  for(int i = 0 ; i < 5 ; i++){
		 System.out.println( "bbbbbbbbbbbbbbbbb"+mapList.get(i));
	 } */

	String dataPoints = gsonObj.toJson(list1);
	String dataPoint1 = gsonObj.toJson(list2);
	String dataPoint2 = gsonObj.toJson(list3);
	String dataPoint3 = gsonObj.toJson(list4);
	String dataPoint4 = gsonObj.toJson(list5);
	// String dataPoint2 = gsonObj.toJson( mappedData.get("2018"));

	System.out.println("dddd" + mapList);
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

		ArrayList<Account> _AccountDetails_1 = new ArrayList<>();

	Gson gsonObj_1 = new Gson();
	Map<Object, Object> map_1 = null;
	List<Map<Object, Object>> list_1 = new ArrayList<Map<Object, Object>>();

	try {

		connection = DBConnection.GetConnection();

		statement = connection.createStatement();

		String _Sql_1 = "SELECT Account_Name ,  sum(Msg_Count) FROM daily_sms_report.account group by Account_Name order by sum(Msg_Count) DESC limit 20";

		resultSet = statement.executeQuery(_Sql_1);

		if (resultSet.next()) {

			// Succesfully excuted the sql statement
		/* 	System.out.println("in in"); */

			do {
	/* 	System.out.println("hhhhhhhhhhh"); */
		// int id = resultSet.getInt(1);
		String _AccountName = resultSet.getString(1);
		// String Date = resultSet.getString(3);

		int _MsgCount = resultSet.getInt(2);

		Account account = new Account(_AccountName, _MsgCount);// Store the results in

		_AccountDetails_1.add(account);// Store details in the arraylist

			} while (resultSet.next()); // Get the employee details and row by row
		}

	} catch (Exception e) {

		e.printStackTrace();
	}

	for (Account value : _AccountDetails_1) {

		String accountName = value.getAccountName();
		int MsgCount = value.getMsgCount();
	/* 	System.out.println(accountName + ",,,,," + MsgCount);
 */
		map_1 = new HashMap<Object, Object>();
		map_1.put("label", accountName);
		map_1.put("y", MsgCount);
		list_1.add(map_1);

	}

	String dataPoints_1 = gsonObj_1.toJson(list_1);
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		ArrayList<Account> _AccountDetails_2 = new ArrayList<>();
	Gson gsonObj_2 = new Gson();
	Map<Object, Object> map_2 = null;
	List<Map<Object, Object>> list_2 = new ArrayList<Map<Object, Object>>();
	String dataPoints_2 = null;

	String xVal, yVal;
	String xVal1, yVal1;

	try {

		connection = DBConnection.GetConnection();

		statement = connection.createStatement();

		String _Sql_2 = "SELECT  Month(Date) , sum(Msg_Count) FROM daily_sms_report.account where Year(Date) = year(curdate()) group by MONTH(Date) ;";

		resultSet = statement.executeQuery(_Sql_2);

		if (resultSet.next()) {

			// Succesfully excuted the sql statement
		/* 	System.out.println("in in"); */

			do {
	/* 	System.out.println("hhhhhhhhhhh"); */
		// int id = resultSet.getInt(1);
		String _AccountName = resultSet.getString(1);
		// String Date = resultSet.getString(3);

		int _MsgCount = resultSet.getInt(2);

		Account account = new Account(_AccountName, _MsgCount);// Store the results in

		_AccountDetails_2.add(account);// Store details in the arraylist

			} while (resultSet.next()); // Get the employee details and row by row
		}

	} catch (Exception e) {

		e.printStackTrace();
	}

	for (Account value : _AccountDetails_2) {

		String accountName = value.getAccountName();
		String month = months[Integer.parseInt(accountName) - 1];
		int MsgCount = value.getMsgCount();

		xVal = month;
		yVal = String.valueOf(MsgCount);

		map_2 = new HashMap<Object, Object>();
		map_2.put("label", xVal);
		map_2.put("y", Double.parseDouble(yVal));
		list_2.add(map_2);
		dataPoints_2 = gsonObj_2.toJson(list_2);

	}
	
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		window.onload = function() {\r\n");
      out.write("			var formatteddata = [];\r\n");
      out.write("			dataPoints =\r\n");
      out.write("	");
out.print(dataPoints);
      out.write("\r\n");
      out.write("		console.log(dataPoints);\r\n");
      out.write("			for ( var key in dataPoints) {\r\n");
      out.write("				var singleObject = {\r\n");
      out.write("					name : '',\r\n");
      out.write("					data : []\r\n");
      out.write("				}\r\n");
      out.write("				singleObject.name = key.toUpperCase();\r\n");
      out.write("				for (var i = 0; i < dataPoints[key].length; i++) {\r\n");
      out.write("					singleObject.data\r\n");
      out.write("							.push(parseInt(dataPoints[key][i].MsgCount));\r\n");
      out.write("				}\r\n");
      out.write("				console.log(singleObject);\r\n");
      out.write("				formatteddata.push(singleObject);\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			drawMultipleLineChart(formatteddata);\r\n");
      out.write("\r\n");
      out.write("			var chart_1 = new CanvasJS.Chart(\"chartContainer_1\", {\r\n");
      out.write("				theme : \"light10\",\r\n");
      out.write("				title : {\r\n");
      out.write("					text : \"\"\r\n");
      out.write("				},\r\n");
      out.write("				axisX : {\r\n");
      out.write("					title : \"Account Name\"\r\n");
      out.write("				},\r\n");
      out.write("				axisY : {\r\n");
      out.write("					title : \"Amount of Messages\",\r\n");
      out.write("					includeZero : true\r\n");
      out.write("				},\r\n");
      out.write("				data : [ {\r\n");
      out.write("					type : \"bar\",\r\n");
      out.write("					yValueFormatString : \"#,##0 messages\",\r\n");
      out.write("					dataPoints :\r\n");
      out.write("	");
out.print(dataPoints_1);
      out.write("\r\n");
      out.write("		} ]\r\n");
      out.write("			});\r\n");
      out.write("			chart_1.render();\r\n");
      out.write("	");
if (dataPoints_2 != null) {
      out.write("\r\n");
      out.write("		var chart_2 = new CanvasJS.Chart(\"chartContainer_2\", {\r\n");
      out.write("				animationEnabled : true,\r\n");
      out.write("				exportEnabled : true,\r\n");
      out.write("				title : {\r\n");
      out.write("					text : \"   \"\r\n");
      out.write("\r\n");
      out.write("				},\r\n");
      out.write("				data : [ {\r\n");
      out.write("					type : \"pie\",\r\n");
      out.write("					indexLabel : \"{label} {x}%\",//change type to bar, line, area, pie, etc\r\n");
      out.write("					dataPoints :\r\n");
      out.write("	");
out.print(dataPoints_2);
      out.write("\r\n");
      out.write("		} ]\r\n");
      out.write("			});\r\n");
      out.write("			chart_2.render();\r\n");
      out.write("	");
}
      out.write("\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		function drawMultipleLineChart(formatteddata) {\r\n");
      out.write("			var chart = new CanvasJS.Chart(\"chartContainer\", {\r\n");
      out.write("				title : {\r\n");
      out.write("					text : \" \"\r\n");
      out.write("				},\r\n");
      out.write("				data : [ {\r\n");
      out.write("					type : \"line\",\r\n");
      out.write("					name : \"2017\",\r\n");
      out.write("					showInLegend : true,\r\n");
      out.write("					dataPoints :\r\n");
      out.write("	");
out.print(dataPoints);
      out.write("\r\n");
      out.write("		}, {\r\n");
      out.write("					type : \"line\",\r\n");
      out.write("					name : \"2018\",\r\n");
      out.write("					showInLegend : true,\r\n");
      out.write("					yValueFormatString : \"#,##0 messages\",\r\n");
      out.write("					dataPoints :\r\n");
      out.write("	");
out.print(dataPoint1);
      out.write("\r\n");
      out.write("		}, {\r\n");
      out.write("					type : \"line\",\r\n");
      out.write("					name : \"2019\",\r\n");
      out.write("					showInLegend : true,\r\n");
      out.write("					yValueFormatString : \"#,##0 messages\",\r\n");
      out.write("					dataPoints :\r\n");
      out.write("	");
out.print(dataPoint2);
      out.write("\r\n");
      out.write("		},\r\n");
      out.write("\r\n");
      out.write("				{\r\n");
      out.write("					type : \"line\",\r\n");
      out.write("					name : \"2020\",\r\n");
      out.write("					showInLegend : true,\r\n");
      out.write("					yValueFormatString : \"#,##0 messages\",\r\n");
      out.write("					dataPoints :\r\n");
      out.write("	");
out.print(dataPoint3);
      out.write("\r\n");
      out.write("		},\r\n");
      out.write("\r\n");
      out.write("				{\r\n");
      out.write("					type : \"line\",\r\n");
      out.write("					name : \"2021\",\r\n");
      out.write("					showInLegend : true,\r\n");
      out.write("					yValueFormatString : \"#,##0 messages\",\r\n");
      out.write("					dataPoints :\r\n");
      out.write("	");
out.print(dataPoint4);
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("				]\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			chart.render();\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"wrapper\">\r\n");
      out.write("		<div class=\"sidebar\" data-image=\"./assets/img/sidebar-5.jpg\"\r\n");
      out.write("			data-color=\"blue\">\r\n");
      out.write("			<!--\r\n");
      out.write("        Tip 1: You can change the color of the sidebar using: data-color=\"purple | blue | green | orange | red\"\r\n");
      out.write("\r\n");
      out.write("        Tip 2: you can also add an image using data-image tag\r\n");
      out.write("    -->\r\n");
      out.write("			<div class=\"sidebar-wrapper\">\r\n");
      out.write("				<div class=\"logo\">\r\n");
      out.write("					<a href=\"#\" class=\"simple-text\"> Textware Daily SMS Count </a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<ul class=\"nav\">\r\n");
      out.write("					<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"index.jsp\"> <i class=\"nc-icon nc-chart-pie-35\"></i>\r\n");
      out.write("							<p>Dashboard</p>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<!-- <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"./index.jsp\">\r\n");
      out.write("                            <i class=\"nc-icon nc-circle-09\"></i>\r\n");
      out.write("                            <p>User Profile</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li> -->\r\n");
      out.write("					<li><a class=\"nav-link\" href=\"ViewSummaryByMonth.jsp\"> <i\r\n");
      out.write("							class=\"nc-icon nc-notes\"></i>\r\n");
      out.write("							<p>Table List</p>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li><a class=\"nav-link\" href=\"MainCharts.jsp\"> <i\r\n");
      out.write("							class=\"nc-icon nc-paper-2\"></i>\r\n");
      out.write("							<p>View Charts</p>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li><a class=\"nav-link\" href=\"upload.jsp\"> <i\r\n");
      out.write("							class=\"nc-icon nc-atom\"></i>\r\n");
      out.write("							<p>Upload</p>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<!--   <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"./maps.html\">\r\n");
      out.write("                            <i class=\"nc-icon nc-pin-3\"></i>\r\n");
      out.write("                            <p>Maps</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"./notifications.html\">\r\n");
      out.write("                            <i class=\"nc-icon nc-bell-55\"></i>\r\n");
      out.write("                            <p>Notifications</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>-->\r\n");
      out.write("					<!--  <li class=\"nav-item active active-pro\">\r\n");
      out.write("                        <a class=\"nav-link active\" href=\"upgrade.html\">\r\n");
      out.write("                            <i class=\"nc-icon nc-alien-33\"></i>\r\n");
      out.write("                            <p>Upgrade to PRO</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li> -->\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"main-panel\">\r\n");
      out.write("			<!-- Navbar -->\r\n");
      out.write("			<nav class=\"navbar navbar-expand-lg \" color-on-scroll=\"500\">\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<a class=\"navbar-brand\" href=\"#pablo\"> Dashboard </a>\r\n");
      out.write("					<button href=\"\" class=\"navbar-toggler navbar-toggler-right\"\r\n");
      out.write("						type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("						aria-controls=\"navigation-index\" aria-expanded=\"false\"\r\n");
      out.write("						aria-label=\"Toggle navigation\">\r\n");
      out.write("						<span class=\"navbar-toggler-bar burger-lines\"></span> <span\r\n");
      out.write("							class=\"navbar-toggler-bar burger-lines\"></span> <span\r\n");
      out.write("							class=\"navbar-toggler-bar burger-lines\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<div class=\"collapse navbar-collapse justify-content-end\"\r\n");
      out.write("						id=\"navigation\">\r\n");
      out.write("						<ul class=\"nav navbar-nav mr-auto\">\r\n");
      out.write("							<li class=\"nav-item\"><a href=\"#\" class=\"nav-link\"\r\n");
      out.write("								data-toggle=\"dropdown\"> <i class=\"nc-icon nc-palette\"></i> <span\r\n");
      out.write("									class=\"d-lg-none\">Dashboard</span>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<!--   <li class=\"dropdown nav-item\">\r\n");
      out.write("                                <a href=\"#\" class=\"dropdown-toggle nav-link\" data-toggle=\"dropdown\">\r\n");
      out.write("                                    <i class=\"nc-icon nc-planet\"></i>\r\n");
      out.write("                                    <span class=\"notification\">5</span>\r\n");
      out.write("                                    <span class=\"d-lg-none\">Notification</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Notification 1</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Notification 2</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Notification 3</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Notification 4</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Another notification</a>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li> -->\r\n");
      out.write("							<!--  <li class=\"nav-item\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                                    <i class=\"nc-icon nc-zoom-split\"></i>\r\n");
      out.write("                                    <span class=\"d-lg-block\">&nbsp;Search</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li> -->\r\n");
      out.write("						</ul>\r\n");
      out.write("						<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("							<!-- <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#pablo\">\r\n");
      out.write("                                    <span class=\"no-icon\">Account</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li> -->\r\n");
      out.write("							<!--   <li class=\"nav-item dropdown\">\r\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" href=\"http://example.com\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                    <span class=\"no-icon\">Dropdown</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Something</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("                                    <div class=\"divider\"></div>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Separated link</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li> -->\r\n");
      out.write("							<!--  <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#pablo\">\r\n");
      out.write("                                    <span class=\"no-icon\">Log out</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>-->\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<!-- End Navbar -->\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-md-4\">\r\n");
      out.write("							<div class=\"card \">\r\n");
      out.write("								<div class=\"card-header \">\r\n");
      out.write("									<h4 class=\"card-title\">Monthly Statistics</h4>\r\n");
      out.write("									<p class=\"card-category\">\r\n");
      out.write("										Monthly Performance for the current year -\r\n");
      out.write("										<script>\r\n");
      out.write("											document.write(new Date()\r\n");
      out.write("													.getFullYear())\r\n");
      out.write("										</script>\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-body \">\r\n");
      out.write("									<!--  <div id=\"chartPreferences\" class=\"ct-chart ct-perfect-fourth\"></div>-->\r\n");
      out.write("									<div id=\"chartContainer_2\" style=\"height: 370px; width: 100%;\"></div>\r\n");
      out.write("									<!--  <div class=\"legend\">\r\n");
      out.write("                                        <i class=\"fa fa-circle text-info\"></i> Open\r\n");
      out.write("                                        <i class=\"fa fa-circle text-danger\"></i> Bounce\r\n");
      out.write("                                        <i class=\"fa fa-circle text-warning\"></i> Unsubscribe\r\n");
      out.write("                                    </div>-->\r\n");
      out.write("									<hr>\r\n");
      out.write("									<!--  <div class=\"stats\">\r\n");
      out.write("                                        <i class=\"fa fa-clock-o\"></i> Campaign sent 2 days ago\r\n");
      out.write("                                    </div> -->\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-8\">\r\n");
      out.write("							<div class=\"card \">\r\n");
      out.write("								<div class=\"card-header \">\r\n");
      out.write("									<h4 class=\"card-title\">Year Behaviour</h4>\r\n");
      out.write("									<p class=\"card-category\">All year perfomance</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-body \">\r\n");
      out.write("									<div id=\"chartContainer\" style=\"height: 370px; width: 100%;\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-footer \">\r\n");
      out.write("									<!-- <div class=\"legend\">\r\n");
      out.write("                                        <i class=\"fa fa-circle text-info\"></i> Open\r\n");
      out.write("                                        <i class=\"fa fa-circle text-danger\"></i> Click\r\n");
      out.write("                                        <i class=\"fa fa-circle text-warning\"></i> Click Second Time\r\n");
      out.write("                                    </div>-->\r\n");
      out.write("									<hr>\r\n");
      out.write("									<!--       <div class=\"stats\">\r\n");
      out.write("                                        <i class=\"fa fa-history\"></i> Updated 3 minutes ago\r\n");
      out.write("                                    </div>-->\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<div class=\"card \">\r\n");
      out.write("								<div class=\"card-header \">\r\n");
      out.write("									<h4 class=\"card-title\">Overall Perfomance of Clients</h4>\r\n");
      out.write("									<p class=\"card-category\">Top 20 Clients</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-body \">\r\n");
      out.write("									<!--<div id=\"chartActivity\" class=\"ct-chart\"></div>-->\r\n");
      out.write("									<div id=\"chartContainer_1\" style=\"height: 370px; width: 100%;\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-footer \">\r\n");
      out.write("									<!--   <div class=\"legend\">\r\n");
      out.write("                                        <i class=\"fa fa-circle text-info\"></i> Tesla Model S\r\n");
      out.write("                                        <i class=\"fa fa-circle text-danger\"></i> BMW 5 Series\r\n");
      out.write("                                    </div> -->\r\n");
      out.write("									<hr>\r\n");
      out.write("									<div class=\"stats\">\r\n");
      out.write("										<i class=\"fa fa-check\"></i> Data information certified\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<div class=\"card  card-tasks\">\r\n");
      out.write("								<div class=\"card-header \">\r\n");
      out.write("									<h4 class=\"card-title\">Select the Date</h4>\r\n");
      out.write("									<p class=\"card-category\">Select the date to review total\r\n");
      out.write("										amount of messages</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-body \">\r\n");
      out.write("									<form action=\"Controller/view_controller3.jsp\" name=\"add\"\r\n");
      out.write("										method=\"post\">\r\n");
      out.write("										<div class=\"input-group\">\r\n");
      out.write("\r\n");
      out.write("											<br> <i class=\"glyphicon glyphicon-user\"></i>\r\n");
      out.write("											&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type=\"date\"\r\n");
      out.write("												name=\"date\"> <input type=\"submit\" value=\"View\"\r\n");
      out.write("												style=\"background-color: #008CBA; padding: 6px 14px; border-radius: 4px; color: white;\" />\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("									</form>\r\n");
      out.write("\r\n");
      out.write("									");

										//String date = (String) request.getAttribute("date");
									//String MsgCount = (String) request.getAttribute("MsgCount");

									String date = (String) application.getAttribute("date");
									String MsgCount = (String) application.getAttribute("MsgCount");
									
      out.write("\r\n");
      out.write("									<br>\r\n");
      out.write("\r\n");
      out.write("									<h5>\r\n");
      out.write("										Date :\r\n");
      out.write("										");

										if (date == null) {
										out.println("Not selected");
									} else {
										out.println(date);
									}
									
      out.write("\r\n");
      out.write("										<div class=\"input-group\">\r\n");
      out.write("											Total Messages :\r\n");
      out.write("\r\n");
      out.write("											");

											if (MsgCount == null) {
										
      out.write("\r\n");
      out.write("\r\n");
      out.write("											<p class=\"x\">\r\n");
      out.write("												");

													out.println("0");
												
      out.write("\r\n");
      out.write("											</p>\r\n");
      out.write("											");

												} else {
											
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("											<center>\r\n");
      out.write("												<h5 class=\"x\">\r\n");
      out.write("													<b> ");

 	out.println(MsgCount);
 
      out.write("\r\n");
      out.write("													</b>\r\n");
      out.write("												</h5>\r\n");
      out.write("											</center>\r\n");
      out.write("\r\n");
      out.write("											");

												}
											
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("									</h5>\r\n");
      out.write("\r\n");
      out.write("									<script type=\"text/javascript\">\r\n");
      out.write("										$(document)\r\n");
      out.write("												.ready(\r\n");
      out.write("														function() {\r\n");
      out.write("															$(\"h5.x\")\r\n");
      out.write("																	.each(\r\n");
      out.write("																			function() {\r\n");
      out.write("																				$(\r\n");
      out.write("																						this)\r\n");
      out.write("																						.html(\r\n");
      out.write("																								parseFloat(\r\n");
      out.write("																										$(\r\n");
      out.write("																												this)\r\n");
      out.write("																												.text())\r\n");
      out.write("																										.toLocaleString(\r\n");
      out.write("																												'en-US',\r\n");
      out.write("																												{\r\n");
      out.write("																													maximumFractionDigits : 2\r\n");
      out.write("																												}));\r\n");
      out.write("																			})\r\n");
      out.write("														})\r\n");
      out.write("									</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-footer \">\r\n");
      out.write("									<hr>\r\n");
      out.write("									<!--   <div class=\"stats\">\r\n");
      out.write("                                        <i class=\"now-ui-icons loader_refresh spin\"></i> Updated 3 minutes ago\r\n");
      out.write("                                    </div>-->\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<footer class=\"footer\">\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<nav>\r\n");
      out.write("						<!--  <ul class=\"footer-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    Home\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    Company\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    Portfolio\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    Blog\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>-->\r\n");
      out.write("						<p class=\"copyright text-center\">\r\n");
      out.write("							©\r\n");
      out.write("							<script>\r\n");
      out.write("								document.write(new Date().getFullYear())\r\n");
      out.write("							</script>\r\n");
      out.write("							mobiOs Private Limited All Rights Reserved\r\n");
      out.write("						</p>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("			</footer>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--   -->\r\n");
      out.write("	<!-- <div class=\"fixed-plugin\">\r\n");
      out.write("    <div class=\"dropdown show-dropdown\">\r\n");
      out.write("        <a href=\"#\" data-toggle=\"dropdown\">\r\n");
      out.write("            <i class=\"fa fa-cog fa-2x\"> </i>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("			<li class=\"header-title\"> Sidebar Style</li>\r\n");
      out.write("            <li class=\"adjustments-line\">\r\n");
      out.write("                <a href=\"javascript:void(0)\" class=\"switch-trigger\">\r\n");
      out.write("                    <p>Background Image</p>\r\n");
      out.write("                    <label class=\"switch\">\r\n");
      out.write("                        <input type=\"checkbox\" data-toggle=\"switch\" checked=\"\" data-on-color=\"primary\" data-off-color=\"primary\"><span class=\"toggle\"></span>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"adjustments-line\">\r\n");
      out.write("                <a href=\"javascript:void(0)\" class=\"switch-trigger background-color\">\r\n");
      out.write("                    <p>Filters</p>\r\n");
      out.write("                    <div class=\"pull-right\">\r\n");
      out.write("                        <span class=\"badge filter badge-black\" data-color=\"black\"></span>\r\n");
      out.write("                        <span class=\"badge filter badge-azure\" data-color=\"azure\"></span>\r\n");
      out.write("                        <span class=\"badge filter badge-green\" data-color=\"green\"></span>\r\n");
      out.write("                        <span class=\"badge filter badge-orange\" data-color=\"orange\"></span>\r\n");
      out.write("                        <span class=\"badge filter badge-red\" data-color=\"red\"></span>\r\n");
      out.write("                        <span class=\"badge filter badge-purple active\" data-color=\"purple\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"header-title\">Sidebar Images</li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"active\">\r\n");
      out.write("                <a class=\"img-holder switch-trigger\" href=\"javascript:void(0)\">\r\n");
      out.write("                    <img src=\"./assets/img/sidebar-1.jpg\" alt=\"\" />\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a class=\"img-holder switch-trigger\" href=\"javascript:void(0)\">\r\n");
      out.write("                    <img src=\"./assets/img/sidebar-3.jpg\" alt=\"\" />\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a class=\"img-holder switch-trigger\" href=\"javascript:void(0)\">\r\n");
      out.write("                    <img src=\".//assets/img/sidebar-4.jpg\" alt=\"\" />\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a class=\"img-holder switch-trigger\" href=\"javascript:void(0)\">\r\n");
      out.write("                    <img src=\"./assets/img/sidebar-5.jpg\" alt=\"\" />\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"button-container\">\r\n");
      out.write("                <div class=\"\">\r\n");
      out.write("                    <a href=\"http://www.creative-tim.com/product/light-bootstrap-dashboard\" target=\"_blank\" class=\"btn btn-info btn-block btn-fill\">Download, it's free!</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"header-title pro-title text-center\">Want more components?</li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"button-container\">\r\n");
      out.write("                <div class=\"\">\r\n");
      out.write("                    <a href=\"http://www.creative-tim.com/product/light-bootstrap-dashboard-pro\" target=\"_blank\" class=\"btn btn-warning btn-block btn-fill\">Get The PRO Version!</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"header-title\" id=\"sharrreTitle\">Thank you for sharing!</li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"button-container\">\r\n");
      out.write("				<button id=\"twitter\" class=\"btn btn-social btn-outline btn-twitter btn-round sharrre\"><i class=\"fa fa-twitter\"></i> · 256</button>\r\n");
      out.write("                <button id=\"facebook\" class=\"btn btn-social btn-outline btn-facebook btn-round sharrre\"><i class=\"fa fa-facebook-square\"></i> · 426</button>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write(" -->\r\n");
      out.write("</body>\r\n");
      out.write("<!--   Core JS Files   -->\r\n");
      out.write("<script src=\"./assets/js/core/jquery.3.2.1.min.js\"\r\n");
      out.write("	type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/js/core/popper.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/js/core/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->\r\n");
      out.write("<script src=\"./assets/js/plugins/bootstrap-switch.js\"></script>\r\n");
      out.write("<!--  Google Maps Plugin    -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE\"></script>\r\n");
      out.write("<!--  Chartist Plugin  -->\r\n");
      out.write("<script src=\"./assets/js/plugins/chartist.min.js\"></script>\r\n");
      out.write("<!--  Notifications Plugin    -->\r\n");
      out.write("<script src=\"./assets/js/plugins/bootstrap-notify.js\"></script>\r\n");
      out.write("<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->\r\n");
      out.write("<script src=\"./assets/js/light-bootstrap-dashboard.js?v=2.0.0 \"\r\n");
      out.write("	type=\"text/javascript\"></script>\r\n");
      out.write("<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->\r\n");
      out.write("<script src=\"./assets/js/demo.js\"></script>\r\n");
      out.write("<!-- <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        // Javascript method's body can be found in assets/js/demos.js\r\n");
      out.write("        demo.initDashboardPageCharts();\r\n");
      out.write("\r\n");
      out.write("        demo.showNotification();\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("</script>  -->\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
