/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-09-07 05:34:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.TreeMap;
import java.awt.Label;
import java.util.Iterator;
import java.util.stream.Collector;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.util.HashMap;
import Operations.SMSdb;
import java.util.List;
import java.util.Map;
import modle.Account;
import java.util.ArrayList;
import com.google.gson.Gson;
import Database.*;

public final class MainCharts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Database");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.awt.Label");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.stream.Collectors");
    _jspx_imports_classes.add("Operations.SMSdb");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.stream.Stream");
    _jspx_imports_classes.add("java.util.TreeMap");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.google.gson.Gson");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.util.stream.Collector");
    _jspx_imports_classes.add("modle.Account");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("=========================================================\r\n");
      out.write(" Light Bootstrap Dashboard - v2.0.1\r\n");
      out.write("=========================================================\r\n");
      out.write("\r\n");
      out.write(" Product Page: https://www.creative-tim.com/product/light-bootstrap-dashboard\r\n");
      out.write(" Copyright 2019 Creative Tim (https://www.creative-tim.com)\r\n");
      out.write(" Licensed under MIT (https://github.com/creativetimofficial/light-bootstrap-dashboard/blob/master/LICENSE)\r\n");
      out.write("\r\n");
      out.write(" Coded by Creative Tim\r\n");
      out.write("\r\n");
      out.write("=========================================================\r\n");
      out.write("\r\n");
      out.write(" The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.  -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"./assets/img/apple-icon.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"./assets/img/favicon.ico\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("    <title>Chart Report | Textware Daily SMS Report</title>\r\n");
      out.write("    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />\r\n");
      out.write("    <!--     Fonts and icons     -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700,200\" rel=\"stylesheet\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\" />\r\n");
      out.write("    <!-- CSS Files -->\r\n");
      out.write("    <link href=\"./assets/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"./assets/css/light-bootstrap-dashboard.css?v=2.0.0 \" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- CSS Just for demo purpose, don't include it in your project -->\r\n");
      out.write("    <link href=\"./assets/css/demo.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <script\r\n");
      out.write("	src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\"\r\n");
      out.write("	type=\"text/javascript\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://canvasjs.com/assets/script/canvasjs.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

		//ArrayList<Account> accounts_1 = db.ViewDatabyDatePerMonthChart(monthNumber);
		
ArrayList<Account> _AccountDetails = new ArrayList<>();

		boolean isSuccess;
		Connection connection;
		Statement statement;
		ResultSet resultSet;
 
		

		String[] months = { "January", "February", "March", "April", "May", "June", "July", "August", "Sepetember",
		"October", "November", "December" };

		String Month = null;
		Gson gsonObj = new Gson();
		Map<Object, Object> map = null;
		List<Map<Object, Object>> list = new ArrayList<Map<Object, Object>>();

		String year = request.getParameter("year");
		String monthNumber = request.getParameter("month");
		if(year==null){
			year="2021";
		}
		if(monthNumber==null){
			monthNumber = "3";
		}
		Month = months[Integer.parseInt(monthNumber) - 1];
		
		try {

			// Call to the database connection
			connection = DBConnection.GetConnection();


			statement = connection.createStatement();

			// Declare the sql statement for retrieve all employee details
		//	String _Sql = "select * from  totalcountmonthlychart where Month= ' " + monthNumber + " ' order by  SumMsgCount desc LIMIT 20";
			String _Sql = "select * from  totalcountmonthlychart where Month= ' " + monthNumber + " ' and YEAR = '" +year + "'order by  SumMsgCount desc LIMIT 20";
			// Execute the sql statement
			resultSet = statement.executeQuery(_Sql);

			if (resultSet.next()) {

				// Succesfully excuted the sql statement
				System.out.println("in in");

				do {
					System.out.println("hhhhhhhhhhh");
					// int id = resultSet.getInt(1);
					String _AccountName = resultSet.getString(1);
					// String Date = resultSet.getString(3);
				
					int _MsgCount = resultSet.getInt(2);
				

					Account account = new Account(_AccountName, _MsgCount);// Store the results in

					_AccountDetails.add(account);// Store details in the arraylist

				}while(resultSet.next()); // Get the employee details and row by row
			}

		} catch (Exception e) {

			e.printStackTrace();
		}

//	SMSdb db = new SMSdb();
	//ArrayList<Account> accounts = db.ViewDatabyMonthlyChart(monthNumber);
//		//ArrayList<Account> accounts = db.ViewDatabyMonthlyChart(monthNumber, year);

		for (Account value :   _AccountDetails) {

			String accountName = value.getAccountName();
			int MsgCount = value.getMsgCount();
			System.out.println( accountName +",,,,,"+  MsgCount);

			map = new HashMap	<Object, Object>();map.put("label", accountName);map.put("y", MsgCount);list.add(map);

		}

		String dataPoints = gsonObj.toJson(list);
		String monthName = gsonObj.toJson(Month);
		String YEAR_1 = gsonObj.toJson(year);
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");

	
	ArrayList<Account> _AccountDetails_1 = new ArrayList<>();
	
	Gson gsonObj_1 = new Gson();
	Map<Object, Object> map_1 = null;
	List<Map<Object, Object>> list_1 = new ArrayList<Map<Object, Object>>();

	String year_1 = request.getParameter("year");

	if (year_1 == null) {
		year_1 = "2021";
	}

	try {

		// Call to the database connection
		connection = DBConnection.GetConnection();

		statement = connection.createStatement();

		// Declare the sql statement for retrieve all employee details
		//	String _Sql = "select * from  totalcountmonthlychart where Month= ' " + monthNumber + " ' order by  SumMsgCount desc LIMIT 20";
		String _Sql_1 = "SELECT Month(Date) , sum(Msg_Count) FROM daily_sms_report.account where YEAR(Date) = '" + year_1
		+ "' group by MONTH(Date)";
		// Execute the sql statement
		resultSet = statement.executeQuery(_Sql_1);

		if (resultSet.next()) {

			// Succesfully excuted the sql statement
			System.out.println("in in");

			do {
		System.out.println("hhhhhhhhhhh");
		// int id = resultSet.getInt(1);
		String _MonthNumber = resultSet.getString(1);
		// String Date = resultSet.getString(3);

		int _MsgCount = resultSet.getInt(2);

		Account account = new Account(_MonthNumber, _MsgCount);// Store the results in

		_AccountDetails_1.add(account);// Store details in the arraylist

			} while (resultSet.next()); // Get the employee details and row by row
		}

	} catch (Exception e) {

		e.printStackTrace();
	}

	//	SMSdb db = new SMSdb();
	//ArrayList<Account> accounts = db.ViewDatabyMonthlyChart(monthNumber);
	//		//ArrayList<Account> accounts = db.ViewDatabyMonthlyChart(monthNumber, year);
	System.out.println("aaaa" + _AccountDetails_1);

	ArrayList<Account> _AccountDetails1 = new ArrayList<>();

	ArrayList<String> monthsAvailable = new ArrayList<>();

	for (Account value : _AccountDetails_1) {

		monthsAvailable.add(value.getAccountName());
	}
	
	Iterator<Account> iter = _AccountDetails_1.iterator();
	ArrayList<Account> toRemoveAccounts = new ArrayList<>();

	try{
	for (int i = 0; i < months.length; i++) {
		for(Account value : _AccountDetails_1) {
				
			
				int tempI = i + 1;
					int month = Integer.parseInt(value.getAccountName());
					
					System.out.println("monthhhh"+month);
					System.out.println("tempppppp"+tempI);
					
			
					if (month == tempI) {
						System.out.println("----msg Countss" + value.getMsgCount());
						map_1 = new HashMap<Object, Object>();
						map_1.put("label", months[i]);
						map_1.put("y", value.getMsgCount());
						list_1.add(map_1);
						toRemoveAccounts.add(value);
						//_AccountDetails.remove(value);
						//iter.remove();
					} else {
						System.out.println("----msg else" + value.getMsgCount());
						map_1 = new HashMap<Object, Object>();
						map_1.put("label", months[i]);
						map_1.put("y", 0);
						list_1.add(map_1);
					}
			
					System.out.println("----msg listt" + _AccountDetails_1.size());
				tempI =0;
			}
		
		_AccountDetails_1.removeAll(toRemoveAccounts);

		System.out.println("iiiiiiii"+i);

		if (_AccountDetails_1.size() == 0) {
			map_1 = new HashMap<Object	, Object>();
			map_1.put("label", months[i]);
			map_1.put("y", 0);
			list_1.add(map_1);
			
			}
	
	
			
	}
		
	}catch(Exception e){
		e.printStackTrace();
	}
		List<Map<Object, Object>> newList_1 = new ArrayList<Map<Object, Object>>();
	
	for(Map e : list_1){
		
		System.out.println("kkkkkkkkkkkk"+e);
		if(!newList_1.contains(e)){
			
			
			newList_1.add(e);
			
		}
	}
	
	Object label = new Object();
	List<Map<Object, Object>> removeList_1 = new ArrayList<Map<Object, Object>>();
	for(Map e : newList_1){
		
		//System.out.println(e.get("label"));
		//System.out.println(e.values());
		if(label.equals(e.get("label"))){
			//do nothing
		if(e.get("y").equals("0"));{
			//newList.remove(e);
			removeList_1.add(e);
		}
		}else{
			//do nothing
		}
		
		label = e.get("label");
		
		
	}
	newList_1.removeAll(removeList_1);
for(Map e : newList_1){
		
		System.out.println(e.get("label"));
		System.out.println(e.values());
		System.out.println();

		
		
		
	}
	String dataPoints_1 = gsonObj.toJson(newList_1);
	String monthName_1 = gsonObj.toJson(year);
	
	
	
	
	
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<script>\r\n");
      out.write("window.onload = function() { \r\n");
      out.write(" \r\n");
      out.write("var chart = new CanvasJS.Chart(\"chartContainer\", {\r\n");
      out.write("	theme: \"light10\",\r\n");
      out.write("	title: {\r\n");
      out.write("		text: 	 ");
out.print(YEAR_1);
      out.write(" +\"   \"+ ");
out.print(monthName);
      out.write("\r\n");
      out.write("	},\r\n");
      out.write("	axisX: {\r\n");
      out.write("		title: \"Account Name\"\r\n");
      out.write("	},\r\n");
      out.write("	axisY: {\r\n");
      out.write("		title: \"Amount of Messages\",\r\n");
      out.write("		includeZero: true\r\n");
      out.write("	},\r\n");
      out.write("	data: [{\r\n");
      out.write("		type: \"bar\",\r\n");
      out.write("		yValueFormatString: \"#,##0 messages\",\r\n");
      out.write("		dataPoints : ");
out.print(dataPoints);
      out.write("\r\n");
      out.write("	}]\r\n");
      out.write("});\r\n");
      out.write("chart.render();\r\n");
      out.write("\r\n");
      out.write("var ddlYears = document.getElementById(\"ddlYears\");\r\n");
      out.write("var ddlYears_1 = document.getElementById(\"ddlYears_1\");\r\n");
      out.write("\r\n");
      out.write("//Determine the Current Year.\r\n");
      out.write("var currentYear = (new Date()).getFullYear();\r\n");
      out.write("\r\n");
      out.write("//Loop and add the Year values to DropDownList.\r\n");
      out.write("for (var i = 2017; i <= currentYear; i++) {\r\n");
      out.write("	var option = document.createElement(\"OPTION\");\r\n");
      out.write("	option.innerHTML = i;\r\n");
      out.write("	option.value = i;\r\n");
      out.write("	ddlYears.appendChild(option);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//Loop and add the Year values to DropDownList.\r\n");
      out.write("for (var i = 2017; i <= currentYear; i++) {\r\n");
      out.write("	var option = document.createElement(\"OPTION\");\r\n");
      out.write("	option.innerHTML = i;\r\n");
      out.write("	option.value = i;\r\n");
      out.write("	ddlYears_1.appendChild(option);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var chart_1 = new CanvasJS.Chart(\"chartContainer_1\", {\r\n");
      out.write("	theme: \"light10\",\r\n");
      out.write("	title: {\r\n");
      out.write("		text: 	\"Year \" + ");
out.print(monthName_1);
      out.write("\r\n");
      out.write("	},\r\n");
      out.write("	axisX: {\r\n");
      out.write("		title: \"Month\"\r\n");
      out.write("	},\r\n");
      out.write("	axisY: {\r\n");
      out.write("		title: \"Amount of Messages\",\r\n");
      out.write("		includeZero: true\r\n");
      out.write("	},\r\n");
      out.write("	data: [{\r\n");
      out.write("		type: \"line\",\r\n");
      out.write("		yValueFormatString: \"#,##0 messages\",\r\n");
      out.write("		dataPoints : ");
out.print(dataPoints_1);
      out.write("\r\n");
      out.write("	}]\r\n");
      out.write("});\r\n");
      out.write("chart_1.render();\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<!-- Overview Main Chart -->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <div class=\"sidebar\" data-image=\"./assets/img/sidebar-5.jpg\"  data-color=\"blue\" >\r\n");
      out.write("            <!--\r\n");
      out.write("        Tip 1: You can change the color of the sidebar using: data-color=\"purple | blue | green | orange | red\"\r\n");
      out.write("\r\n");
      out.write("        Tip 2: you can also add an image using data-image tag\r\n");
      out.write("    -->\r\n");
      out.write("            <div class=\"sidebar-wrapper\">\r\n");
      out.write("                <div class=\"logo\">\r\n");
      out.write("                    <a href=\"#\" class=\"simple-text\">\r\n");
      out.write("                     Textware Daily SMS Count \r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"nav\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"index.jsp\">\r\n");
      out.write("                            <i class=\"nc-icon nc-chart-pie-35\"></i>\r\n");
      out.write("                            <p>Dashboard</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  <!-- <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"./index.jsp\">\r\n");
      out.write("                            <i class=\"nc-icon nc-circle-09\"></i>\r\n");
      out.write("                            <p>User Profile</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li> -->  \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"ViewSummaryByMonth.jsp\">\r\n");
      out.write("                            <i class=\"nc-icon nc-notes\"></i>\r\n");
      out.write("                            <p>Table List</p>\r\n");
      out.write("                            \r\n");
      out.write("                        </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                    <li class=\"nav-item active\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"MainCharts.jsp\">\r\n");
      out.write("                            <i class=\"nc-icon nc-paper-2\"></i>\r\n");
      out.write("                            <p>View Charts</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"upload.jsp\">\r\n");
      out.write("                            <i class=\"nc-icon nc-atom\"></i>\r\n");
      out.write("                            <p>Upload</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  <!--   <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"./maps.html\">\r\n");
      out.write("                            <i class=\"nc-icon nc-pin-3\"></i>\r\n");
      out.write("                            <p>Maps</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"./notifications.html\">\r\n");
      out.write("                            <i class=\"nc-icon nc-bell-55\"></i>\r\n");
      out.write("                            <p>Notifications</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>--> \r\n");
      out.write("                   <!--  <li class=\"nav-item active active-pro\">\r\n");
      out.write("                        <a class=\"nav-link active\" href=\"upgrade.html\">\r\n");
      out.write("                            <i class=\"nc-icon nc-alien-33\"></i>\r\n");
      out.write("                            <p>Upgrade to PRO</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li> -->\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"main-panel\">\r\n");
      out.write("            <!-- Navbar -->\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg \" color-on-scroll=\"500\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"#pablo\"> Chart Report </a>\r\n");
      out.write("                    <button href=\"\" class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" aria-controls=\"navigation-index\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                        <span class=\"navbar-toggler-bar burger-lines\"></span>\r\n");
      out.write("                        <span class=\"navbar-toggler-bar burger-lines\"></span>\r\n");
      out.write("                        <span class=\"navbar-toggler-bar burger-lines\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse justify-content-end\" id=\"navigation\">\r\n");
      out.write("                        <ul class=\"nav navbar-nav mr-auto\">\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link\" data-toggle=\"dropdown\">\r\n");
      out.write("                                    <i class=\"nc-icon nc-palette\"></i>\r\n");
      out.write("                                    <span class=\"d-lg-none\">Dashboard</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                         <!--   <li class=\"dropdown nav-item\">\r\n");
      out.write("                                <a href=\"#\" class=\"dropdown-toggle nav-link\" data-toggle=\"dropdown\">\r\n");
      out.write("                                    <i class=\"nc-icon nc-planet\"></i>\r\n");
      out.write("                                    <span class=\"notification\">5</span>\r\n");
      out.write("                                    <span class=\"d-lg-none\">Notification</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Notification 1</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Notification 2</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Notification 3</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Notification 4</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Another notification</a>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li> --> \r\n");
      out.write("                          <!--  <li class=\"nav-item\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                                    <i class=\"nc-icon nc-zoom-split\"></i>\r\n");
      out.write("                                    <span class=\"d-lg-block\">&nbsp;Search</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li> --> \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                            <!-- <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#pablo\">\r\n");
      out.write("                                    <span class=\"no-icon\">Account</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li> -->\r\n");
      out.write("                         <!--   <li class=\"nav-item dropdown\">\r\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" href=\"http://example.com\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                    <span class=\"no-icon\">Dropdown</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Something</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("                                    <div class=\"divider\"></div>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Separated link</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li> --> \r\n");
      out.write("                              <!--  <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#pablo\">\r\n");
      out.write("                                    <span class=\"no-icon\">Log out</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>--> \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <!-- End Navbar -->\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-lg-12\" >\r\n");
      out.write("                            <div class=\"card \" style=\"\"width:100%\">\r\n");
      out.write("                                <div class=\"card-header \">\r\n");
      out.write("                                    <h4 class=\"card-title\">Monthly Behaviour</h4>\r\n");
      out.write("                                    <p class=\"card-category\">Top 20 Clients</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body \">\r\n");
      out.write("                                \r\n");
      out.write("                                <form action=\"MainCharts.jsp\" name=\"add\" method=\"post\">\r\n");
      out.write("		\r\n");
      out.write("			<div class=\"input-group\">\r\n");
      out.write("\r\n");
      out.write("				Select the Year<i\r\n");
      out.write("					class=\"glyphicon glyphicon-user\"></i>&nbsp;&nbsp; <select\r\n");
      out.write("					id=\"ddlYears\" name=\"year\">\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					</select> &nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("			Select the Month<i\r\n");
      out.write("				class=\"glyphicon glyphicon-user\"></i> &nbsp;&nbsp;<select\r\n");
      out.write("				name=\"month\" id=\"monthNumber1\">\r\n");
      out.write("				<option value=\"1\">January</option>\r\n");
      out.write("				<option value=\"2\">February</option>\r\n");
      out.write("				<option value=\"3\">March</option>\r\n");
      out.write("				<option value=\"4\">April</option>\r\n");
      out.write("				<option value=\"5\">May</option>\r\n");
      out.write("				<option value=\"6\">June</option>\r\n");
      out.write("				<option value=\"7\">July</option>\r\n");
      out.write("				<option value=\"8\">August</option>\r\n");
      out.write("				<option value=\"9\">September</option>\r\n");
      out.write("				<option value=\"10\">October</option>\r\n");
      out.write("				<option value=\"11\">November</option>\r\n");
      out.write("				<option value=\"12\">December</option>\r\n");
      out.write("			</select>&nbsp;&nbsp;&nbsp;&nbsp; <input type=\"submit\" value=\"Show Chart\" style=\"background-color: #008CBA ; padding: 6px 14px; border-radius: 4px; color: white;\">\r\n");
      out.write("		</form>\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                  <div id=\"chartContainer\" style=\"height: 370px; width: 100%;\"></div>\r\n");
      out.write("                                    	\r\n");
      out.write("                                    	\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-footer \">\r\n");
      out.write("                                   <!-- <div class=\"legend\">\r\n");
      out.write("                                        <i class=\"fa fa-circle text-info\"></i> Open\r\n");
      out.write("                                        <i class=\"fa fa-circle text-danger\"></i> Click\r\n");
      out.write("                                        <i class=\"fa fa-circle text-warning\"></i> Click Second Time\r\n");
      out.write("                                    </div>-->\r\n");
      out.write("                                    <hr>\r\n");
      out.write("                                    <div class=\"stats\">\r\n");
      out.write("                                        <i class=\"fa fa-history\"></i> Updated 3 minutes ago\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <br><br><br>\r\n");
      out.write("                    <div class=\"row\" style=\"width : 100%;\">\r\n");
      out.write("                        <div class=\"col-lg-12\" style=\"width : 100%;\">\r\n");
      out.write("                            <div class=\"card \">\r\n");
      out.write("                                <div class=\"card-header \">\r\n");
      out.write("                                    <h4 class=\"card-title\">Overall Perfomance per Year</h4>\r\n");
      out.write("                                 <p class=\"card-category\">Shows the overview for the selected year</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body \">\r\n");
      out.write("                                    <!--<div id=\"chartActivity\" class=\"ct-chart\"></div>-->\r\n");
      out.write("                                    <form action=\"MainCharts.jsp\" name=\"add\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"input-group\">\r\n");
      out.write("\r\n");
      out.write("				Select the Year<i\r\n");
      out.write("					class=\"glyphicon glyphicon-user\"></i> &nbsp;&nbsp; <select\r\n");
      out.write("					id=\"ddlYears_1\" name=\"year\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</select> &nbsp;&nbsp;&nbsp;&nbsp; <input type=\"submit\" value=\"Show Chart\" style=\"background-color: #008CBA ; padding: 6px 14px; border-radius: 4px; color: white;\">\r\n");
      out.write("		</form>\r\n");
      out.write("                                     	<div id=\"chartContainer_1\" style=\"height: 370px; width: 100%;\"></div>\r\n");
      out.write("                                     	\r\n");
      out.write("                                     	\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-footer \">\r\n");
      out.write("                                  <!--   <div class=\"legend\">\r\n");
      out.write("                                        <i class=\"fa fa-circle text-info\"></i> Tesla Model S\r\n");
      out.write("                                        <i class=\"fa fa-circle text-danger\"></i> BMW 5 Series\r\n");
      out.write("                                    </div> -->\r\n");
      out.write("                                    <hr>\r\n");
      out.write("                                    <div class=\"stats\">\r\n");
      out.write("                                        <i class=\"fa fa-check\"></i> Data information certified\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                   \r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <footer class=\"footer\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <nav>\r\n");
      out.write("                        <!--  <ul class=\"footer-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    Home\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    Company\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    Portfolio\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    Blog\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>-->\r\n");
      out.write("                        <p class=\"copyright text-center\">\r\n");
      out.write("                            ©\r\n");
      out.write("                            <script>\r\n");
      out.write("                                document.write(new Date().getFullYear()) \r\n");
      out.write("                            </script>\r\n");
      out.write("                      mobiOs Private Limited All Rights Reserved\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--   -->\r\n");
      out.write("    <!-- <div class=\"fixed-plugin\">\r\n");
      out.write("    <div class=\"dropdown show-dropdown\">\r\n");
      out.write("        <a href=\"#\" data-toggle=\"dropdown\">\r\n");
      out.write("            <i class=\"fa fa-cog fa-2x\"> </i>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("			<li class=\"header-title\"> Sidebar Style</li>\r\n");
      out.write("            <li class=\"adjustments-line\">\r\n");
      out.write("                <a href=\"javascript:void(0)\" class=\"switch-trigger\">\r\n");
      out.write("                    <p>Background Image</p>\r\n");
      out.write("                    <label class=\"switch\">\r\n");
      out.write("                        <input type=\"checkbox\" data-toggle=\"switch\" checked=\"\" data-on-color=\"primary\" data-off-color=\"primary\"><span class=\"toggle\"></span>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"adjustments-line\">\r\n");
      out.write("                <a href=\"javascript:void(0)\" class=\"switch-trigger background-color\">\r\n");
      out.write("                    <p>Filters</p>\r\n");
      out.write("                    <div class=\"pull-right\">\r\n");
      out.write("                        <span class=\"badge filter badge-black\" data-color=\"black\"></span>\r\n");
      out.write("                        <span class=\"badge filter badge-azure\" data-color=\"azure\"></span>\r\n");
      out.write("                        <span class=\"badge filter badge-green\" data-color=\"green\"></span>\r\n");
      out.write("                        <span class=\"badge filter badge-orange\" data-color=\"orange\"></span>\r\n");
      out.write("                        <span class=\"badge filter badge-red\" data-color=\"red\"></span>\r\n");
      out.write("                        <span class=\"badge filter badge-purple active\" data-color=\"purple\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"header-title\">Sidebar Images</li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"active\">\r\n");
      out.write("                <a class=\"img-holder switch-trigger\" href=\"javascript:void(0)\">\r\n");
      out.write("                    <img src=\"./assets/img/sidebar-1.jpg\" alt=\"\" />\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a class=\"img-holder switch-trigger\" href=\"javascript:void(0)\">\r\n");
      out.write("                    <img src=\"./assets/img/sidebar-3.jpg\" alt=\"\" />\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a class=\"img-holder switch-trigger\" href=\"javascript:void(0)\">\r\n");
      out.write("                    <img src=\".//assets/img/sidebar-4.jpg\" alt=\"\" />\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a class=\"img-holder switch-trigger\" href=\"javascript:void(0)\">\r\n");
      out.write("                    <img src=\"./assets/img/sidebar-5.jpg\" alt=\"\" />\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"button-container\">\r\n");
      out.write("                <div class=\"\">\r\n");
      out.write("                    <a href=\"http://www.creative-tim.com/product/light-bootstrap-dashboard\" target=\"_blank\" class=\"btn btn-info btn-block btn-fill\">Download, it's free!</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"header-title pro-title text-center\">Want more components?</li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"button-container\">\r\n");
      out.write("                <div class=\"\">\r\n");
      out.write("                    <a href=\"http://www.creative-tim.com/product/light-bootstrap-dashboard-pro\" target=\"_blank\" class=\"btn btn-warning btn-block btn-fill\">Get The PRO Version!</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"header-title\" id=\"sharrreTitle\">Thank you for sharing!</li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"button-container\">\r\n");
      out.write("				<button id=\"twitter\" class=\"btn btn-social btn-outline btn-twitter btn-round sharrre\"><i class=\"fa fa-twitter\"></i> · 256</button>\r\n");
      out.write("                <button id=\"facebook\" class=\"btn btn-social btn-outline btn-facebook btn-round sharrre\"><i class=\"fa fa-facebook-square\"></i> · 426</button>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write(" -->\r\n");
      out.write("</body>\r\n");
      out.write("<!--   Core JS Files   -->\r\n");
      out.write("<script src=\"./assets/js/core/jquery.3.2.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/js/core/popper.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/js/core/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->\r\n");
      out.write("<script src=\"./assets/js/plugins/bootstrap-switch.js\"></script>\r\n");
      out.write("<!--  Google Maps Plugin    -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE\"></script>\r\n");
      out.write("<!--  Chartist Plugin  -->\r\n");
      out.write("<script src=\"./assets/js/plugins/chartist.min.js\"></script>\r\n");
      out.write("<!--  Notifications Plugin    -->\r\n");
      out.write("<script src=\"./assets/js/plugins/bootstrap-notify.js\"></script>\r\n");
      out.write("<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->\r\n");
      out.write("<script src=\"./assets/js/light-bootstrap-dashboard.js?v=2.0.0 \" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->\r\n");
      out.write("<script src=\"./assets/js/demo.js\"></script>\r\n");
      out.write("<!-- <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        // Javascript method's body can be found in assets/js/demos.js\r\n");
      out.write("        demo.initDashboardPageCharts();\r\n");
      out.write("\r\n");
      out.write("        demo.showNotification();\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("</script>  -->\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
