/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-09-07 05:34:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Database.DBConnection;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import Operations.SMSdb;
import java.util.TreeMap;
import java.util.List;
import java.util.Set;
import java.util.Map;
import java.util.ArrayList;
import modle.Data;
import modle.Account;
import java.text.DateFormat;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;

public final class test7_005f7_1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1614843924000L));
    _jspx_dependants.put("jar:file:/D:/D/Coding%20Projects/Eclipse%20Workspace/Dialy_SMS_Count_Report/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Daily_SMS_Report/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("Operations.SMSdb");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.TreeMap");
    _jspx_imports_classes.add("modle.Data");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("Database.DBConnection");
    _jspx_imports_classes.add("modle.Account");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("  <script src=\"http://code.jquery.com/ui/1.10.4/jquery-ui.js\"></script>\r\n");
      out.write("   <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"./assets/img/apple-icon.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"./assets/img/favicon.ico\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("    <title>Main Table Report | Daily SMS Report</title>\r\n");
      out.write("    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />\r\n");
      out.write("    <!--     Fonts and icons     -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700,200\" rel=\"stylesheet\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\" />\r\n");
      out.write("    <!-- CSS Files -->\r\n");
      out.write("    <link href=\"./assets/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"./assets/css/light-bootstrap-dashboard.css?v=2.0.0 \" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- CSS Just for demo purpose, don't include it in your project -->\r\n");
      out.write("    <link href=\"./assets/css/demo.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"jquery-3.3.1.min.js\">\r\n");
      out.write("	\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.3.1.min.js\"\r\n");
      out.write("	integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("	src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("	src=\"https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("td {\r\n");
      out.write("	height: 0.1px;\r\n");
      out.write("}\r\n");
      out.write("th, td {\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("  }\r\n");
      out.write(".l {\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".u {\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	background-color: #333;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 12px 14px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li a:hover {\r\n");
      out.write("	background-color: #111;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#active {\r\n");
      out.write("	background-color: #FF4D4D;\r\n");
      out.write("	height: 43px;\r\n");
      out.write("}\r\n");
      out.write("#myTable tr{\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

		TreeMap<String, List<Data>> all = new TreeMap<>();
	SMSdb db = new SMSdb();
	String month = request.getParameter("month");
	String year = request.getParameter("year");
	ArrayList<String> dates = new ArrayList();
	ArrayList<String> totalCounts = new ArrayList();
	String totalCountPermonth = "0";
	
	String[] months = {"January", "February", "March", "April", "May", "June", "July", "August", "Sepetember", "October",
			"November", "December"};
	
	boolean isSuccess;
	Connection connection;
	Statement statement;
	ResultSet resultSet;

	if (month == null) {

		month = "3";
	}
	if (year == null) {
		year = "2021";
	}

	ArrayList<String> accountNames = new ArrayList();
	ArrayList<String> newAccountNames = new ArrayList();
	ArrayList<Account> accNames = new ArrayList();

	try {

		connection = DBConnection.GetConnection();

		statement = connection.createStatement();

		String _Sql = "select * from account where MONTH(Date) = '" + month + " ' and Year(Date) = '" + year + "'";
		// String _Sql = "select id , Account_Name , Date , sum(Msg_Count) as 'SUM' from
		// daily_sms_report.account where MONTH(Date) = '"+monthNumber+"' group by
		// Account_Name order by SUM DESC";
		resultSet = statement.executeQuery(_Sql);

		if (resultSet.next()) {

			System.out.println("in in");

			do {
				int _Id = resultSet.getInt(1);
				String _AccountName = resultSet.getString(2);
				String _Date = resultSet.getString(3);
				int _MsgCount = resultSet.getInt(4);

				System.out.println("View Data by Monthlyyyyyyyyyyy" + _AccountName);
				Account account = new Account(_Id, _AccountName, _Date, _MsgCount);

				accNames.add(account);

			} while (resultSet.next());
		}

	} catch (Exception e) {

		e.printStackTrace();
	}


		//accNames = SMSdb.ViewDatabyMonthly(month);
		totalCountPermonth = db.TotalMsgsPerMonth(month);
	

	for (Account values : accNames) {

		accountNames.add(values.getAccountName());
		//System.out.println("rrrrr"+values.getAccountName());

	}

	for (String values : accountNames) {

		if (!newAccountNames.contains(values)) {
			newAccountNames.add(values);
		}

	}

	Calendar cal = Calendar.getInstance();
	cal.set(Calendar.MONTH, (Integer.parseInt(month) - 1));
	cal.set(Calendar.YEAR, Integer.parseInt(year));
	cal.set(Calendar.DAY_OF_MONTH, 1);
	int maxDay = cal.getActualMaximum(Calendar.DAY_OF_MONTH);
	Date dateobj = new Date();

	//Get the date of current date
	DateFormat df1 = new SimpleDateFormat("dd");
	String today = df1.format(dateobj);

	//Get the date of current date and month and year
	DateFormat df2 = new SimpleDateFormat("yyyy-MM");
	String today1 = df2.format(dateobj);

	SimpleDateFormat df = new SimpleDateFormat("dd");
	System.out.println(df.format(cal.getTime()));
	String date = df.format(cal.getTime());
	
	SimpleDateFormat df5 = new SimpleDateFormat("yyyy-MM-dd");
	System.out.println(df5.format(cal.getTime()));
	String date5 = df5.format(cal.getTime());
	System.out.println("Date55555  "+date5);

	SimpleDateFormat df3 = new SimpleDateFormat("yyyy-MM");
	System.out.println(df3.format(cal.getTime()));
	String date1 = df3.format(cal.getTime());

	System.out.println("Current Date : " + today);
	System.out.println("Current Date dddd : " + today1);
	System.out.println("Selected Date : " + date);

	if (date1.equals(today1)) {
		for (int i = 0; i < Integer.parseInt(today); i++) {
			// ResultSet query = DBConnection.getDbCon().query("select * from acc where month(date)='3' and day(date)='"+i+"'");
			ArrayList<Account> accounts = db.ViewDatabyMonthDate1(month, year, String.valueOf(i + 1));
			List<String> names = new ArrayList<>();
			for (Account var : accounts) {
		names.add(var.getAccountName());
			}
			List<Data> a = new ArrayList<>();

			cal.set(Calendar.DAY_OF_MONTH, i + 1);
			dates.add(df.format(cal.getTime()));
			String MsgCount = db.TotalMsgsPerDay(df5.format(cal.getTime()));
			totalCounts.add(MsgCount);

			for (String v : newAccountNames) {

		if (names.contains(v)) {

			for (Account x : accounts) {

				if (x.getAccountName().equals(v)) {
					a.add(new Data(x.getAccountName(), String.valueOf(x.getMsgCount()), df.format(cal.getTime())));
				}
			}
		} else {

			a.add(new Data(v, "0", df.format(cal.getTime())));
		}

			}

			all.put(df.format(cal.getTime()), a);
		}
	} else {
		for (int i = 0; i < maxDay; i++) {
			// ResultSet query = DBConnection.getDbCon().query("select * from acc where month(date)='3' and day(date)='"+i+"'");
			ArrayList<Account> accounts = db.ViewDatabyMonthDate1(month, year, String.valueOf(i + 1));
			List<String> names = new ArrayList<>();
			for (Account var : accounts) {
		names.add(var.getAccountName());
			}
			List<Data> a = new ArrayList<>();

			cal.set(Calendar.DAY_OF_MONTH, i + 1);
			dates.add(df.format(cal.getTime()));
			String MsgCount = db.TotalMsgsPerDay(df5.format(cal.getTime()));
			totalCounts.add(MsgCount);

			for (String v : newAccountNames) {

		if (names.contains(v)) {

			for (Account x : accounts) {

				if (x.getAccountName().equals(v)) {
					a.add(new Data(x.getAccountName(), String.valueOf(x.getMsgCount()), df.format(cal.getTime())));
				}
			}
		} else {

			a.add(new Data(v, "0", df.format(cal.getTime())));
		}

			}

			all.put(df.format(cal.getTime()), a);
		}
	}

	Set<Map.Entry<String, List<Data>>> entries = all.entrySet();

	System.out.println("sssssssssssssss " + entries.size());

	for (Map.Entry<String, List<Data>> entry : entries) {

		//System.out.println("datesss"+entry.getKey());
	}

	for (Map.Entry<String, List<Data>> entry : entries) {

		// System.out.println("Size"+entry.getValue().size());
		if (entry.getValue().size() == 0) {
			System.out.println("0");
		} else {
			for (Data datas : entry.getValue()) {
		/// System.out.println(datas.toString());
			}
		}

		;

	}

	System.out.println(newAccountNames);
	
	System.out.println("Size = " + newAccountNames.size());
	application.setAttribute("newAccountNames", newAccountNames);
	application.setAttribute("dates", dates);
	application.setAttribute("totalCounts", totalCounts);
	application.setAttribute("totalCountPermonth", totalCountPermonth);
	application.setAttribute("month",month);
	application.setAttribute("year",year);

	//response.sendRedirect("test.jsp");
	//response.sendRedirect(request.getContextPath() + "test.jsp");
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"wrapper\">\r\n");
      out.write("        <div class=\"sidebar\" data-image=\"./assets/img/sidebar-5.jpg\"  data-color=\"blue\">\r\n");
      out.write("            <!--\r\n");
      out.write("        Tip 1: You can change the color of the sidebar using: data-color=\"purple | blue | green | orange | red\"\r\n");
      out.write("\r\n");
      out.write("        Tip 2: you can also add an image using data-image tag\r\n");
      out.write("    -->\r\n");
      out.write("            <div class=\"sidebar-wrapper\">\r\n");
      out.write("                <div class=\"logo\">\r\n");
      out.write("                    <a href=\"http://www.creative-tim.com\" class=\"simple-text\">\r\n");
      out.write("                         Textware Daily SMS Count \r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"nav\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"index.jsp\">\r\n");
      out.write("                            <i class=\"nc-icon nc-chart-pie-35\"></i>\r\n");
      out.write("                            <p>Dashboard</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  <!-- <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"./index.jsp\">\r\n");
      out.write("                            <i class=\"nc-icon nc-circle-09\"></i>\r\n");
      out.write("                            <p>User Profile</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li> --> \r\n");
      out.write("                    <li class=\"nav-item active\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"test7_7.1.jsp\">\r\n");
      out.write("                            <i class=\"nc-icon nc-notes\"></i>\r\n");
      out.write("                            <p>Table List</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"MainCharts.jsp\">\r\n");
      out.write("                            <i class=\"nc-icon nc-paper-2\"></i>\r\n");
      out.write("                            <p>View Charts</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                   <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"upload.jsp\">\r\n");
      out.write("                            <i class=\"nc-icon nc-atom\"></i>\r\n");
      out.write("                            <p>Upload</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <!--   <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"./maps.html\">\r\n");
      out.write("                            <i class=\"nc-icon nc-pin-3\"></i>\r\n");
      out.write("                            <p>Maps</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"./notifications.html\">\r\n");
      out.write("                            <i class=\"nc-icon nc-bell-55\"></i>\r\n");
      out.write("                            <p>Notifications</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>--> \r\n");
      out.write("                   <!--  <li class=\"nav-item active active-pro\">\r\n");
      out.write("                        <a class=\"nav-link active\" href=\"upgrade.html\">\r\n");
      out.write("                            <i class=\"nc-icon nc-alien-33\"></i>\r\n");
      out.write("                            <p>Upgrade to PRO</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li> -->\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"main-panel\">\r\n");
      out.write("            <!-- Navbar -->\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg \" color-on-scroll=\"500\" style=\"color: #808080\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"#pablo\"> Table Report - Main Table</a>\r\n");
      out.write("                    <button href=\"\" class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" aria-controls=\"navigation-index\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                        <span class=\"navbar-toggler-bar burger-lines\"></span>\r\n");
      out.write("                        <span class=\"navbar-toggler-bar burger-lines\"></span>\r\n");
      out.write("                        <span class=\"navbar-toggler-bar burger-lines\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse justify-content-end\" id=\"navigation\">\r\n");
      out.write("                        <ul class=\"nav navbar-nav mr-auto\">\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link\" data-toggle=\"dropdown\">\r\n");
      out.write("                                    <i class=\"nc-icon nc-palette\"></i>\r\n");
      out.write("                                    <span class=\"d-lg-none\">Dashboard</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                         <!--    <li class=\"dropdown nav-item\">\r\n");
      out.write("                                <a href=\"#\" class=\"dropdown-toggle nav-link\" data-toggle=\"dropdown\">\r\n");
      out.write("                                    <i class=\"nc-icon nc-planet\"></i>\r\n");
      out.write("                                    <span class=\"notification\">5</span>\r\n");
      out.write("                                    <span class=\"d-lg-none\">Notification</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Notification 1</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Notification 2</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Notification 3</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Notification 4</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Another notification</a>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                                    <i class=\"nc-icon nc-zoom-split\"></i>\r\n");
      out.write("                                    <span class=\"d-lg-block\">&nbsp;Search</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#pablo\">\r\n");
      out.write("                                    <span class=\"no-icon\">Account</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item dropdown\">\r\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" href=\"http://example.com\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                    <span class=\"no-icon\">Dropdown</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Something</a>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("                                    <div class=\"divider\"></div>\r\n");
      out.write("                                    <a class=\"dropdown-item\" href=\"#\">Separated link</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#pablo\">\r\n");
      out.write("                                    <span class=\"no-icon\">Log out</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>-->\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <!-- End Navbar -->\r\n");
      out.write("	<br>\r\n");
      out.write("	 <div class=\"container\">\r\n");
      out.write("          <ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("	          <li class=\"nav-item\">\r\n");
      out.write("		          <a class=\"nav-link {{request () -> is('ViewSummaryByMonth.jsp') ? 'active' : null }}\"  href=\"ViewSummaryByMonth.jsp\" role=\"tab\" style=\"color: #808080\">View Summary By Month</a>\r\n");
      out.write("	          </li>\r\n");
      out.write("	          <li class=\"nav-item\">\r\n");
      out.write("		        <a class=\"nav-link {{request () -> is('View_2.jsp') ? 'active' : null }}\" href=\"View_2.jsp\" role=\"tab\" style=\"color: #808080\">View Summary By Date</a>\r\n");
      out.write("	          </li>\r\n");
      out.write("	          \r\n");
      out.write("	            <li class=\"nav-item\">\r\n");
      out.write("		        <a class=\"nav-link  active {{request () -> is('test7_7.1.jsp') ? 'active' : null }}\" href=\"test7_7.1.jsp\" role=\"tab\" style=\"color: #808080\">Overall View</a>\r\n");
      out.write("	          </li>\r\n");
      out.write("	\r\n");
      out.write("          </ul><!-- Tab panes -->\r\n");
      out.write("        <div class=\"tab-content\">\r\n");
      out.write("	<div class=\"tab-pane {{request() ->is('ViewSummaryByMonth.jsp') ? 'active' : null }}\" id=\"{{url('ViewSummaryByMonth.jsp')}}\" role=\"tabpanel\">\r\n");
      out.write("		<p>View Summary By Month</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"tab-pane {{request() ->is('View_2.jsp') ? 'active' : null }}\" id=\"{{url('View_2.jsp')}}\" role=\"tabpanel\">\r\n");
      out.write("		<p>View Summary By Date</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"tab-pane {{request() ->is('test7_7.1.jsp') ? 'active' : null }}\" id=\"{{url('test7_7.1.jsp')}}\" role=\"tabpanel\">\r\n");
      out.write("		<p>Overall View</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"text-center\"></div>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"test7_7.1.jsp\" name=\"add\" method=\"post\">\r\n");
      out.write("			<div class=\"input-group\">\r\n");
      out.write("\r\n");
      out.write("				Year &nbsp;&nbsp; <select \r\n");
      out.write("					id=\"ddlYears\" name=\"year\"></select> &nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("			 Month &nbsp;&nbsp;<select\r\n");
      out.write("					name=\"month\" id=\"monthName\">\r\n");
      out.write("					<option value=\"1\">January</option>\r\n");
      out.write("					<option value=\"2\">February</option>\r\n");
      out.write("					<option value=\"3\">March</option>\r\n");
      out.write("					<option value=\"4\">April</option>\r\n");
      out.write("					<option value=\"5\">May</option>\r\n");
      out.write("					<option value=\"6\">June</option>\r\n");
      out.write("					<option value=\"7\">July</option>\r\n");
      out.write("					<option value=\"8\">August</option>\r\n");
      out.write("					<option value=\"9\">September</option>\r\n");
      out.write("					<option value=\"10\">October</option>\r\n");
      out.write("					<option value=\"11\">November</option>\r\n");
      out.write("					<option value=\"12\">December</option>\r\n");
      out.write("				</select>&nbsp;&nbsp;&nbsp;&nbsp; <input type=\"submit\" value=\"View\" style=\"background-color: #008CBA ; padding: 6px 10px; border-radius: 4px; color: white;\"/>\r\n");
      out.write("				 \r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("	\r\n");
      out.write("			\r\n");
      out.write("			<h3>");
      out.print(year);
      out.write("        ");
      out.print(months[Integer.parseInt(month)-1]);
      out.write("</h3>\r\n");
      out.write("			\r\n");
      out.write("	</div>\r\n");
      out.write(" <div id=\"\" title=\"Basic dialog\">\r\n");
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	<table class=\"table table-striped\" id=\"myTable\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<thead>\r\n");
      out.write("			<tr>\r\n");
      out.write("\r\n");
      out.write("				<th>Account Name</th>\r\n");
      out.write("				");

					for (int i = 0; i < dates.size(); i++) {
				
      out.write("\r\n");
      out.write("				<th>");
      out.print(dates.get(i));
      out.write("</th>\r\n");
      out.write("				");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<th id=\"total\">Total</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tbody>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");

				for (int i = 0; i < newAccountNames.size(); i++) {
			
      out.write("\r\n");
      out.write("	\r\n");
      out.write("			<tr onclick=\"passData('");
      out.print(newAccountNames.get(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(application.getAttribute("month"));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(application.getAttribute("year"));
      out.write("');\">\r\n");
      out.write("			<td name=\"name\" onclick=\"passData('");
      out.print(newAccountNames.get(i));
      out.write('\'');
      out.write(',');
      out.print(dates.get(1));
      out.write(");\">");
      out.print(newAccountNames.get(i));
      out.write("</td>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("				");

					int total = 0;

				for (Map.Entry<String, List<Data>> entry : entries) {

					if (entry.getValue().size() == 0) {
						//System.out.println("0");
				
      out.write("\r\n");
      out.write("				<td>0</td>\r\n");
      out.write("\r\n");
      out.write("				");

					} else {
					for (Data datas : entry.getValue()) {
						for (int j = 0; j < dates.size(); j++) {
					//  System.out.println(datas.toString());

					if (newAccountNames.get(i).equals(datas.getName()) && datas.getDate().equals(dates.get(j))) {
				
      out.write("\r\n");
      out.write("				<td style=\"text-align: right\" class=\"contribution\">");
      out.print(datas.getCount());
      out.write("</td>\r\n");
      out.write("				");

					total = total + Integer.parseInt(datas.getCount());
				}

				}
				}

				;
				}
				}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<td headers=\"total\" class=\"contribution\">");
      out.print(total);
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<tr style=\"background-color: #ff0000\">\r\n");
      out.write("				<td>Total</td>\r\n");
      out.write("				");

					for (int i = 0; i < totalCounts.size(); i++) {
				
      out.write("\r\n");
      out.write("				<td class=\"contribution\">");
      out.print(totalCounts.get(i));
      out.write("</td>\r\n");
      out.write("				");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<td class=\"contribution\">");
      out.print(totalCountPermonth);
      out.write("</td>\r\n");
      out.write("			<tr>\r\n");
      out.write("		</tbody>\r\n");
      out.write("	</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document).ready(function() {\r\n");
      out.write("			$('#myTable').DataTable({\r\n");
      out.write("\r\n");
      out.write("				\"columns\" : [ {\r\n");
      out.write("					\"type\" : \"number\",\r\n");
      out.write("					\"thousandSeparator\" : \",\"\r\n");
      out.write("				} ]\r\n");
      out.write("\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		window.onload = function() {\r\n");
      out.write("			//Reference the DropDownList.\r\n");
      out.write("			var ddlYears = document.getElementById(\"ddlYears\");\r\n");
      out.write("\r\n");
      out.write("			//Determine the Current Year.\r\n");
      out.write("			var currentYear = (new Date()).getFullYear();\r\n");
      out.write("\r\n");
      out.write("			//Loop and add the Year values to DropDownList.\r\n");
      out.write("			for (var i = 2017; i <= currentYear; i++) {\r\n");
      out.write("				var option = document.createElement(\"OPTION\");\r\n");
      out.write("				option.innerHTML = i;\r\n");
      out.write("				option.value = i;\r\n");
      out.write("				ddlYears.appendChild(option);\r\n");
      out.write("			}\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		$(document).ready(\r\n");
      out.write("				function() {\r\n");
      out.write("					$(\"td.contribution\").each(\r\n");
      out.write("							function() {\r\n");
      out.write("								$(this).html(\r\n");
      out.write("										parseFloat($(this).text())\r\n");
      out.write("												.toLocaleString('en-US', {\r\n");
      out.write("													maximumFractionDigits : 2\r\n");
      out.write("												}));\r\n");
      out.write("							})\r\n");
      out.write("				})\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	function passData(name , month , year){\r\n");
      out.write("			console.log(\"kkkkk\"+name);\r\n");
      out.write("			localStorage.setItem(\"name1\",name);\r\n");
      out.write("			//var month = document.getElementById(\"monthName\").value;\r\n");
      out.write("				console.log(\"Monthhhh\"+month);\r\n");
      out.write("				console.log(\"Yearrrrr\"+year);\r\n");
      out.write("				\r\n");
      out.write("		var array = [];\r\n");
      out.write("		array.push(name);\r\n");
      out.write("		array.push(month);\r\n");
      out.write("		array.push(year);\r\n");
      out.write("		\r\n");
      out.write("			//window.location(\"1.jsp?name11=\"+name);\r\n");
      out.write("			\r\n");
      out.write("		//window.location = \"1.jsp?\"+name;\r\n");
      out.write("			//location.assign(\"1.jsp?name11=\"+name);\r\n");
      out.write("			location.assign(\"2_2.jsp?name11=\"+array);\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("	<br><br><br><br><br>\r\n");
      out.write("	 <footer class=\"footer\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <nav>\r\n");
      out.write("                      <!--  \\  <ul class=\"footer-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    Home\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    Company\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    Portfolio\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    Blog\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>-->\r\n");
      out.write("                        <p class=\"copyright text-center\">\r\n");
      out.write("                            ©\r\n");
      out.write("                            <script>\r\n");
      out.write("                                document.write(new Date().getFullYear())\r\n");
      out.write("                            </script>\r\n");
      out.write("                            mobiOs Private Limited All Rights Reserved\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
